version: '3.3'

services:
  backend:
    image: openjdk:8-jre-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./server/build/libs:/usr/src/sausage
      - ./server/build/resources/main/application-default.yml:/usr/src/sausage/config
    working_dir: /usr/src/sausage
    entrypoint:
      - java
      - -Djava.security.egd=file:/dev/./urandom
      - -jar
      - server.jar

  database:
    ports:
      - "5432:5432"
