swagger: '2.0'

info:
  version: "0.0.0"
  title: <enter your title>

# Describe your paths here
paths:
  /persons:
    get:
      description: |
        Gets `Person` objects.
        Optional query param of **size** determines
        size of returned array
      parameters:
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfPersons
            type: array
            items:
              $ref: '#/definitions/person'

    post:
      summary: Updates user
      consumes:
        - application/json
      parameters:
        - name: person
          in: body
          schema:
            $ref: '#/definitions/person'
      responses:
        200:
          description: OK

definitions:
  person:
    description: User of the app
    type: object
    required:
      - name
    properties:
      id:
        description: Surogate ID
        type: integer
        example: 42
      name:
        description: First and last name
        type: string
      age:
        type: integer
      addresses:
        type: array
        items:  
          $ref: '#/definitions/address'
      
  address:
    type: object
    properties:
      street: 
        type: string
      city: 
        type: string
        
      